sudo: false
language: android
dist: trusty


jdk:
  - oraclejdk11
  
env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_ABI=arm64-v8a
    - ANDROID_TAG=google_apis
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=23
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)

before_install:
 - chmod +x gradlew


  

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.3
    
    - tools
    - platform-tools
    - tools

    # The SDK version used to compile your project
    - android-23
    - android-29
    
    - extra-android-m2repository
    
    - sys-img-armeabi-v7a-android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
    
before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  
